name: Test suite

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test-bigquery:
        runs-on: buildjet-4vcpu-ubuntu-2204
        timeout-minutes: 10
        env:
            BQ_TEST_PROJECT: ${{ secrets.BQ_PROJECT_CI}}
            BQ_TEST_DATASET: we_ci_${{ github.sha }}_${{ github.run_id }}_${{ github.run_attempt }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Auth google
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.BQ_CREDENTIALS_JSON_CI }}
                  project_id: ${{ env.BQ_TEST_PROJECT }}
                  create_credentials_file: true
            - name: execute py script
              run: python carto_extension.py test

    test-snowflake:
        runs-on: buildjet-4vcpu-ubuntu-2204
        timeout-minutes: 10
        env:
            SF_ACCOUNT: ${{ secrets.SF_ACCOUNT_CI }}
            SF_USER: ${{ secrets.SF_USER_CI }}
            SF_PASSWORD: ${{ secrets.SF_PASSWORD_CI }}
            SF_TEST_DATABASE: ${{ secrets.SF_DATABASE_CI }}
            SF_TEST_SCHEMA: extension_ci_${{ github.sha }}_${{ github.run_id }}_${{ github.run_attempt }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: execute py script
              run: python carto_extension.py test
